# Generated by Django 3.0.5 on 2020-04-27 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=300)),
                ('brand_email', models.CharField(max_length=500)),
                ('brand_password', models.CharField(max_length=500)),
                ('brand_phoneno', models.CharField(max_length=200)),
                ('brand_adddress', models.CharField(max_length=1000)),
                ('brand_short_descriptions', models.TextField()),
                ('brand_descriptions', models.TextField()),
                ('brand_join_date', models.DateTimeField(auto_now_add=True)),
                ('is_active_brand', models.BooleanField(default=False, verbose_name='Is Active Brand')),
                ('is_verified_brand', models.BooleanField(default=False, verbose_name='Is Brand Verified')),
                ('email_verificationid', models.CharField(default='bibekitsnotvalid', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_titel', models.CharField(default='', max_length=200)),
                ('campaign_country', models.CharField(default='', max_length=200)),
                ('platform', models.CharField(default='', max_length=100)),
                ('campaign_type', models.CharField(default='', max_length=100)),
                ('ads_category', models.CharField(default='', max_length=100)),
                ('ads_url', models.CharField(default='', max_length=100)),
                ('is_shipping_product', models.BooleanField(default=True, verbose_name='IS_Shipping_Product')),
                ('about_product_or_service', models.TextField(default='', max_length=5000)),
                ('campaign_listing_duration', models.CharField(default='', max_length=50)),
                ('about_campaign', models.TextField(default='', max_length=5000)),
                ('exact_requirement', models.TextField(default='', max_length=5000)),
                ('traget_audience', models.CharField(default='', max_length=100)),
                ('project_budget', models.CharField(default='', max_length=100)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Under Verification', max_length=100)),
                ('is_admin_approved', models.BooleanField(default=False, verbose_name='Is Admin Approved')),
                ('is_project_rejected', models.BooleanField(default=False, verbose_name='Is Project Rejected')),
                ('is_payment_done', models.BooleanField(default=False, verbose_name='Is Payment Done')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainwebsite.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_first_name', models.CharField(default='', max_length=300)),
                ('creator_last_name', models.CharField(default='', max_length=300)),
                ('creator_email', models.CharField(default='', max_length=500)),
                ('creator_password', models.CharField(max_length=500)),
                ('creator_phoneno', models.CharField(max_length=200)),
                ('creator_adddress', models.CharField(max_length=1000)),
                ('creator_short_descriptions', models.TextField(default='')),
                ('creator_descriptions', models.TextField(default='')),
                ('creator_platform_identification_id', models.CharField(default='', max_length=50000)),
                ('creator_join_date', models.DateTimeField(auto_now_add=True)),
                ('is_active_creator', models.BooleanField(default=False, verbose_name='Is Active Creator')),
                ('is_verified_creator', models.BooleanField(default=False, verbose_name='Is Creator Verified')),
                ('email_verificationid', models.CharField(default='bibekitsnotvalid', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Youtubechannels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_channelid', models.CharField(max_length=200)),
                ('youtube_viewcount', models.CharField(max_length=100)),
                ('youtube_commentcount', models.CharField(max_length=100)),
                ('youtube_subscribercount', models.CharField(max_length=100)),
                ('youtube_videocount', models.CharField(max_length=100)),
                ('youtube_channelname', models.CharField(max_length=200)),
                ('youtube_profileurl', models.CharField(max_length=1000)),
                ('channeladded_date', models.DateTimeField(auto_now_add=True)),
                ('creator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainwebsite.Creator')),
            ],
        ),

        migrations.CreateModel(
            name='Creatorinivitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('is_creator_accept_request', models.BooleanField(default=False, verbose_name='Is Creator Accepted The Request')),
                ('is_creator_reject_request', models.BooleanField(default=False, verbose_name='Is Creator Rejected The Request')),
                ('is_project_submited', models.BooleanField(default=False, verbose_name='Is Project Submitted')),
                ('is_project_delivered', models.BooleanField(default=False, verbose_name='Is Project Delivered')),
                ('status', models.CharField(max_length=200)),
                ('campaign_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Campaign', to='mainwebsite.Campaign')),
                ('creator_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Creator', to='mainwebsite.Creator')),
            ],
        ),
        migrations.AddField(
            model_name='creator',
            name='creator_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainwebsite.Platform'),
        ),
    ]
