# Generated by Django 3.0.5 on 2020-04-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0007_brands_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='unquie_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='brands_invitation',
            name='unquie_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='unquie_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='creator',
            name='unquie_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='creatorinivitation',
            name='unquie_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='unquie_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='submitedcampaign',
            name='unquie_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='youtubechannels',
            name='unquie_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
